"""initial schema

Revision ID: 36bbae24c38c
Revises:
Create Date: 2026-06-18 11:07:22.015978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36bbae24c38c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exception_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "traceback_id", sa.String(length=64), nullable=False, comment="异常跟踪ID"
        ),
        sa.Column(
            "exception_type", sa.String(length=100), nullable=False, comment="异常类型"
        ),
        sa.Column(
            "error_code", sa.String(length=100), nullable=True, comment="错误代码"
        ),
        sa.Column("exception_message", sa.Text(), nullable=False, comment="异常消息"),
        sa.Column("status_code", sa.Integer(), nullable=True, comment="HTTP状态码"),
        sa.Column("method", sa.String(length=10), nullable=True, comment="HTTP方法"),
        sa.Column("endpoint", sa.String(length=255), nullable=True, comment="请求端点"),
        sa.Column("request_id", sa.String(length=64), nullable=True, comment="请求ID"),
        sa.Column("user_id", sa.String(length=64), nullable=True, comment="用户ID"),
        sa.Column(
            "ip_address", sa.String(length=45), nullable=True, comment="客户端IP地址"
        ),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="用户代理"),
        sa.Column("details", sa.JSON(), nullable=True, comment="异常详细信息"),
        sa.Column("traceback", sa.Text(), nullable=True, comment="异常堆栈"),
        sa.Column("context", sa.JSON(), nullable=True, comment="异常上下文信息"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, comment="创建时间"
        ),
        sa.Column("is_resolved", sa.Boolean(), nullable=False, comment="是否已解决"),
        sa.Column(
            "resolved_at", sa.DateTime(timezone=True), nullable=True, comment="解决时间"
        ),
        sa.Column("resolved_by", sa.String(length=64), nullable=True, comment="解决人"),
        sa.Column("resolution_notes", sa.Text(), nullable=True, comment="解决备注"),
        sa.Column("severity", sa.String(length=20), nullable=False, comment="严重程度"),
        sa.Column("priority", sa.String(length=20), nullable=False, comment="优先级"),
        sa.Column(
            "parent_exception_id", sa.Integer(), nullable=True, comment="父异常ID"
        ),
        sa.Column(
            "related_incident_id",
            sa.String(length=64),
            nullable=True,
            comment="关联事件ID",
        ),
        sa.Column(
            "response_time_ms", sa.Float(), nullable=True, comment="响应时间(毫秒)"
        ),
        sa.ForeignKeyConstraint(
            ["parent_exception_id"],
            ["exception_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_created_at_severity",
        "exception_logs",
        ["created_at", "severity"],
        unique=False,
    )
    op.create_index(
        "idx_error_code_created",
        "exception_logs",
        ["error_code", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_exception_type_created",
        "exception_logs",
        ["exception_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_is_resolved_created",
        "exception_logs",
        ["is_resolved", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_status_code_created",
        "exception_logs",
        ["status_code", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_traceback_id_user",
        "exception_logs",
        ["traceback_id", "user_id"],
        unique=False,
    )
    op.create_index(
        "idx_user_id_created", "exception_logs", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_exception_logs_created_at"),
        "exception_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_endpoint"), "exception_logs", ["endpoint"], unique=False
    )
    op.create_index(
        op.f("ix_exception_logs_error_code"),
        "exception_logs",
        ["error_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_exception_type"),
        "exception_logs",
        ["exception_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_id"), "exception_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_exception_logs_priority"), "exception_logs", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_exception_logs_related_incident_id"),
        "exception_logs",
        ["related_incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_request_id"),
        "exception_logs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_severity"), "exception_logs", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_exception_logs_status_code"),
        "exception_logs",
        ["status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_traceback_id"),
        "exception_logs",
        ["traceback_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exception_logs_user_id"), "exception_logs", ["user_id"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_exception_logs_user_id"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_traceback_id"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_status_code"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_severity"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_request_id"), table_name="exception_logs")
    op.drop_index(
        op.f("ix_exception_logs_related_incident_id"), table_name="exception_logs"
    )
    op.drop_index(op.f("ix_exception_logs_priority"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_id"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_exception_type"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_error_code"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_endpoint"), table_name="exception_logs")
    op.drop_index(op.f("ix_exception_logs_created_at"), table_name="exception_logs")
    op.drop_index("idx_user_id_created", table_name="exception_logs")
    op.drop_index("idx_traceback_id_user", table_name="exception_logs")
    op.drop_index("idx_status_code_created", table_name="exception_logs")
    op.drop_index("idx_is_resolved_created", table_name="exception_logs")
    op.drop_index("idx_exception_type_created", table_name="exception_logs")
    op.drop_index("idx_error_code_created", table_name="exception_logs")
    op.drop_index("idx_created_at_severity", table_name="exception_logs")
    op.drop_table("exception_logs")
    # ### end Alembic commands ###
